name:                effects-experiments
version:             0.1.0.0
github:              "willisplummer/effects-experiments"
license:             BSD3
author:              "willis plummer"
maintainer:          "willisplummer@gmail.com"
copyright:           "2020 willis plummer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/willisplummer/effects-experiments#readme>

dependencies:
- base >= 4.7 && < 5
- yael
- transformers
- monad-logger
- mtl

library:
  source-dirs: src

executables:
  effects-experiments-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - effects-experiments

tests:
  effects-experiments-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - effects-experiments
